#Server container properties
server:
  port: 8084
#Spring properties
spring:
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_HOST:http://localhost:9411/}
    service:
      name: orders-service
    sender:
      type: web
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: orders
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    discovery:
      client:
        simple:
          instances:
            address-service:
              - uri: ${ADDRESS_SERVICE_URI:http://localhost:8081}
            users-service:
              - uri: ${USERS_SERVICE_URI:http://localhost:8082}
            hotels-service:
              - uri: ${HOTELS_SERVICE_URI:http://localhost:8083}
            payments-service:
              - uri: ${PAYMENT_SERVICE_URI:http://localhost:8085}
#Actuator props
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true

#Logger props
logging:
  level:
    root: info
feign:
  circuitbreaker:
    enabled: true
resilience4j:
  circuitbreaker:
    instances:
      orderCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 60
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      orderCircuitBreaker:
        registerHealthIndicator: true
        maxRetryAttempts: 3
        waitDuration: 2s
        slowCallRateThreshold: 150
  ratelimiter:
    instances:
      orderCircuitBreaker:
        registerHealthIndicator: false
        limitForPeriod: 5
        limitRefreshPeriod: 50
        timeoutDuration: 3s