server:
  port: 8888

spring:
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_HOST:http://localhost:9411/}
    service:
      name: gateway-service
    sender:
      type: web
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #        Route address
        - id: addressService
          uri: ${ADDRESS_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/addresses/**
        #        Route users
        - id: usersService
          uri: ${USERS_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/v1/users/**
        #        Route hotels
        - id: hotelsService
          uri: ${HOTELS_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/v1/hotels/**
        #        Route orders
        - id: ordersService
          uri: ${ORDERS_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/api/v1/orders/**
        # Card routes
        - id: paymentService
          uri: ${PAYMENT_SERVICE_URI:http://localhost:8085}
          predicates:
            - Path=/api/v1/payments/**