# Servlet container properties
server:
  port: 8085

# Spring properties
spring:
  application:
    name: payments-service
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    lettuce:
      shutdown-timeout: 150ms
    database: 0

# Actuator properties
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
#Logger
logging:
  level:
    root: info
