server:
  port: 8890

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RostFromLv/spring-config
          default-label: master
          username:
          password:
