# Servlet container properties
server:
  port: 8081
# Spring properties
spring:
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_HOST:http://localhost:9411/}
    service:
      name: address-service
    sender:
      type: web
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: booking-api
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

# Actuator properties
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
#Logger
logging:
  level:
    root: info
